### ISSUE TITLE
Lock dependencies

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/network-of-terms-comunica#1]
I checked out this package and it seems not to be working correctly with the latest vendor versions. 😢

Suggestions:

* Check in the `package-lock.json` to ensure we get a working setup any time in the future.
* Stick to Comunica 1.12.* for now, unless https://github.com/comunica/comunica/issues/669 (a regression in 1.13.0) is fixed.

**Comment by ddeboer** [comment]
The fix for https://github.com/comunica/comunica/issues/669 was tagged as 1.13.1, which solves my issues.

@sdevalk So all that’s left to do here is check in the lock file.

**Comment by sdevalk** [comment]
Added [package-lock.json](https://github.com/netwerk-digitaal-erfgoed/network-of-terms-comunica/commit/982e3786d2e0b6f9f4127ba99d208d83350cdcc6).

Note that it also contains all packages needed for development (`devDependencies`), not just the packages needed for running the prototype (`dependencies`). We can change this at some point.

**Comment by ddeboer** [comment]
> Note that it also contains all packages needed for development 

AFAIK that’s fine: `npm install|ci` in production mode should prevent them from being installed.
