### ISSUE TITLE
Bug: quoting `bif:contains` breaks certain queries

### ISSUE THREAD

**Issue by sdevalk** [netwerk-digitaal-erfgoed/network-of-terms-comunica#14]
[Last week's fix](https://github.com/netwerk-digitaal-erfgoed/network-of-terms-comunica/pull/12) introduces a new bug:

If I execute the query...

`bin/run sources:query --identifiers nta --query "Wieringa" --loglevel info`

...the relevant part of the SPARQL query looks like this:

`?label <bif:contains> "'Wieringa'"^^<http://www.w3.org/2001/XMLSchema#string>.`

Although the apostrophe isn't necessary, this query returns terms. However, if I execute the query...

`bin/run sources:query --identifiers nta --query "Wieringa OR Mulisch" --loglevel info`

... the relevant part of the SPARQL query looks like this:

`?label <bif:contains> "'Wieringa OR Mulisch'"^^<http://www.w3.org/2001/XMLSchema#string>.`

This query doesn't return terms. The previous version of the code - without the fix - did.

The part of the SPARQL query should look like this, without apostrophe:

`?label <bif:contains> "Wieringa OR Mulisch"^^<http://www.w3.org/2001/XMLSchema#string>.`

My guess is that we should find a way to only add apostrophes if the search query of the user doesn't contain operators such as OR or AND.

**Comment by ddeboer** [comment]
Yeah, I’m seeing this, too. Additionally, for CHT, which uses `FILTER(CONTAINS…))` I cannot get multi-word search strings to work at all.

**Comment by ddeboer** [comment]
A little overview of our current fulltext situation:

| Sources | Operators  | Use quotes  | Wildcards | Function  | 
|---|---|---|---|---|
| NMVW, NTA, RKDartists  | AND, OR  | `van AND gogh` vs `'van gogh'`   | ? |  `bif:contains()`  | 
| AAT  | AND, OR  | never  | ? | Lucene  |
| CHT  | no  | never  | ? | `contains()`  | 
| Wikidata-entities  | no (only supports literal matches) | never | ?  | `mwapi:search()`   |
