### ISSUE TITLE
Remove unused HDT and TPF distributions

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/network-of-terms-comunica#2]
These will not be used by the Network of Terms due to performance issues, so let’s remove them from `catalog.ttl`. The NoT will use SPARQL only (for now).

**Comment by sdevalk** [comment]
[Removed unused distributions and queries](https://github.com/netwerk-digitaal-erfgoed/network-of-terms-comunica/commit/33d8158a7722b7d725ae2c179a8fa1c7eaa1ac69).
