### ISSUE TITLE
Example query returns an error

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/network-of-terms-comunica#20]
See the following example query in the README.md:
bin/run sources:query --identifiers nta --query "'Wier*'"

This returns the following error: Error: Invalid SPARQL endpoint (http://data.bibliotheken.nl/sparql) response: undefined

More example queries have problems, please check them or correct the README.

**Comment by sdevalk** [comment]
This seems to be a bug in Comunica. I've reported these recently in [this issue](https://github.com/comunica/comunica/issues/704).

**Comment by EnnoMeijers** [comment]
Ok, let's hope this will be fixed soon. The bug description filed at Comunica suggests that there is a generic problem with certain endpoints. But in my tests some queries work and others don't on the same endpoint, looks like it is related to parsing the query and passing it to the endpoint...

**Comment by ddeboer** [comment]
Possibly related to #14.
